### PR TITLE
NEW: Add Docker support

### PR DESCRIPTION
**Pull request by LucasGandel**
This commit add a Docker file allowing to easily build
and test the project.

### CODE REVIEW

**Comment by LucasGandel** [comment]
Once this pull request is merged, an automated build will be created on the DockerHub kitware/kwstyle organization. After that, a new pull request will add circleCI support using this Docker image.

**Comment by aylward** [comment]
Looks good to me.

**Comment by LucasGandel** [comment]
screenshot from 2015-10-27 14 41 05
@thewtex : circleCI checks are failing when creating the image. It is not the first time I get this error, I used to have it randomly on my computer, when the build.sh script is trying to install the build-essential packages. It looks like it can't find the perl package...

**Comment by thewtex** [comment]
@LucasGandel Yes, there is some issue that randomly occurs with the network connection.  I restarted the build via the CircleCI web interface.

**Comment by thewtex** [comment]
Looks great!

Could you please add a commit that renames the ReadMe.txt to README.txt or README.rst or README.md, adds content from here:

  https://kitware.github.io/KWStyle/

And adds the CircleCI status badge?

**Comment by LucasGandel** [comment]
@Matt: Thanks for your help!
No problem I'll modify the ReadMe.txt to a .md one. For the status badge, I can't check the links because I don't have access to kitware/kwstyle in circleCI, but I suppose they should be : 
.. image:: https://circleci.com/gh/Kitware/KWStyle.svg?style=svg
    :target: https://circleci.com/gh/Kitware/KWStyle

**Comment by LucasGandel** [comment]
@thewtex : Changes made. but real BUG this time. This line needed ReadMe.txt in CMakeLists.txt : 
SET(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/ReadMe.txt")

Should I replace the file by README.md or even delete the line? 
After that we should be all set. Sorry for the inconvenience.

**Comment by thewtex** [comment]
Cool.  Yes, please update the path.

The Markdown code for the badge is (the other is restructuredText):

[Circle CI](https://circleci.com/gh/Kitware/KWStyle
)

**Pull request merged**
