### PR TITLE
cppcheck --quiet --force --enable=warning,style,performance,portabili…

### PR DESCRIPTION
**Pull request by RyDroid**
…ty metaCommand.cxx

### CODE REVIEW

**Comment by aylward** [comment]
LGTM!

**Comment by RyDroid** [comment]
What "LGTM" means?

**Comment by aylward** [comment]
"Looks good to me."

Sorry, might just be a phrase used in some small circles.   This is a great
example of why abbreviations for variable names in code can also be a bad
idea. :)

---
Sent via phone.

**Comment by RyDroid** [comment]
Ok. It may be widespread for people that speaks frequently English, but I am not in this case.

**Pull request merged**
